/**
 * Shared helper for fetching and parsing Qlik Sense product-info.js.
 *
 * Centralises the AMD-wrapper stripping and JSON extraction so that all
 * consumers (platform adapters, dialogs, etc.) stay in sync when the
 * upstream format changes.
 */

import logger from './logger';

/** @type {{ version: string | null, releaseLabel: string } | null} */
let cached = null;

/**
 * Parse the raw text of product-info.js into a plain object.
 *
 * Handles two known AMD wrapper formats:
 *   1. `define([], function() { return { … }; });`
 *   2. `define([], / ** @owner ... * / { ... });`
 *
 * @param {string} text - Raw response body.
 * @returns {{ version: string | null, releaseLabel: string } | null}
 */
export function parseProductInfoText(text) {
    let jsonStr;
    const jsonMatch = text.match(/return\s*(\{[\s\S]*\})\s*;?\s*\}\s*\)\s*;?\s*$/);

    if (jsonMatch) {
        jsonStr = jsonMatch[1];
    } else {
        const firstBrace = text.indexOf('{');
        const lastBrace = text.lastIndexOf('}');
        if (firstBrace !== -1 && lastBrace !== -1 && firstBrace < lastBrace) {
            jsonStr = text.substring(firstBrace, lastBrace + 1);
        }
    }

    if (!jsonStr) return null;

    let info;
    try {
        info = JSON.parse(jsonStr);
    } catch (err) {
        logger.warn('product-info.js JSON parse failed:', err);
        return null;
    }
    const comp = info?.composition ?? {};
    return {
        version: comp.version ?? null,
        releaseLabel: comp.releaseLabel ?? '',
    };
}

/**
 * Fetch and parse Qlik Sense version info from product-info.js.
 *
 * The result is cached so repeated calls don't trigger extra network requests.
 *
 * @returns {Promise<{ version: string, releaseLabel: string } | null>}
 */
export async function fetchSenseVersionInfo() {
    if (cached) return cached;

    try {
        const resp = await fetch('/resources/autogenerated/product-info.js');
        if (!resp.ok) {
            logger.warn(`product-info.js fetch failed: ${resp.status}`);
            return null;
        }

        const parsed = parseProductInfoText(await resp.text());

        if (!parsed || !parsed.version) {
            logger.warn('product-info.js did not contain a version');
            return null;
        }

        cached = parsed;
        logger.info(`Sense version detected: ${parsed.version} (${parsed.releaseLabel})`);
        return cached;
    } catch (err) {
        logger.warn('Sense version detection failed:', err);
        return null;
    }
}

/**
 * Convenience: fetch version info and return a human-readable label.
 *
 * @returns {Promise<string>} e.g. `"February 2024 (v14.187.4)"` or `"(unavailable)"`.
 */
export async function fetchSenseVersionLabel() {
    const info = await fetchSenseVersionInfo();
    if (!info) return '(unavailable)';
    return (info.releaseLabel || 'Unknown') + ' (v' + (info.version || '?') + ')';
}
